// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dirsync.proto

package dirsync

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SyncEvent_SyncState int32

const (
	SyncEvent_UNKNOWN  SyncEvent_SyncState = 0
	SyncEvent_IDLE     SyncEvent_SyncState = 1
	SyncEvent_IN_SYNC  SyncEvent_SyncState = 2
	SyncEvent_COMPLETE SyncEvent_SyncState = 3
)

var SyncEvent_SyncState_name = map[int32]string{
	0: "UNKNOWN",
	1: "IDLE",
	2: "IN_SYNC",
	3: "COMPLETE",
}

var SyncEvent_SyncState_value = map[string]int32{
	"UNKNOWN":  0,
	"IDLE":     1,
	"IN_SYNC":  2,
	"COMPLETE": 3,
}

func (x SyncEvent_SyncState) String() string {
	return proto.EnumName(SyncEvent_SyncState_name, int32(x))
}

func (SyncEvent_SyncState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c01ab58cc791b3a, []int{2, 0}
}

type Config struct {
	Syncs                []*Sync  `protobuf:"bytes,1,rep,name=syncs,proto3" json:"syncs,omitempty"`
	LastRun              int64    `protobuf:"varint,2,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c01ab58cc791b3a, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetSyncs() []*Sync {
	if m != nil {
		return m.Syncs
	}
	return nil
}

func (m *Config) GetLastRun() int64 {
	if m != nil {
		return m.LastRun
	}
	return 0
}

type Sync struct {
	Dir                  string       `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Subdir               string       `protobuf:"bytes,2,opt,name=subdir,proto3" json:"subdir,omitempty"`
	Servers              []string     `protobuf:"bytes,3,rep,name=servers,proto3" json:"servers,omitempty"`
	LastSyncTime         int64        `protobuf:"varint,4,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	TimeToSync           []int64      `protobuf:"varint,5,rep,packed,name=time_to_sync,json=timeToSync,proto3" json:"time_to_sync,omitempty"`
	Events               []*SyncEvent `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Sync) Reset()         { *m = Sync{} }
func (m *Sync) String() string { return proto.CompactTextString(m) }
func (*Sync) ProtoMessage()    {}
func (*Sync) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c01ab58cc791b3a, []int{1}
}

func (m *Sync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sync.Unmarshal(m, b)
}
func (m *Sync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sync.Marshal(b, m, deterministic)
}
func (m *Sync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sync.Merge(m, src)
}
func (m *Sync) XXX_Size() int {
	return xxx_messageInfo_Sync.Size(m)
}
func (m *Sync) XXX_DiscardUnknown() {
	xxx_messageInfo_Sync.DiscardUnknown(m)
}

var xxx_messageInfo_Sync proto.InternalMessageInfo

func (m *Sync) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *Sync) GetSubdir() string {
	if m != nil {
		return m.Subdir
	}
	return ""
}

func (m *Sync) GetServers() []string {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *Sync) GetLastSyncTime() int64 {
	if m != nil {
		return m.LastSyncTime
	}
	return 0
}

func (m *Sync) GetTimeToSync() []int64 {
	if m != nil {
		return m.TimeToSync
	}
	return nil
}

func (m *Sync) GetEvents() []*SyncEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

type SyncEvent struct {
	FromServer           string              `protobuf:"bytes,1,opt,name=from_server,json=fromServer,proto3" json:"from_server,omitempty"`
	ToServer             string              `protobuf:"bytes,2,opt,name=to_server,json=toServer,proto3" json:"to_server,omitempty"`
	State                SyncEvent_SyncState `protobuf:"varint,3,opt,name=state,proto3,enum=dirsync.SyncEvent_SyncState" json:"state,omitempty"`
	StartTime            int64               `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64               `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SyncEvent) Reset()         { *m = SyncEvent{} }
func (m *SyncEvent) String() string { return proto.CompactTextString(m) }
func (*SyncEvent) ProtoMessage()    {}
func (*SyncEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c01ab58cc791b3a, []int{2}
}

func (m *SyncEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncEvent.Unmarshal(m, b)
}
func (m *SyncEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncEvent.Marshal(b, m, deterministic)
}
func (m *SyncEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncEvent.Merge(m, src)
}
func (m *SyncEvent) XXX_Size() int {
	return xxx_messageInfo_SyncEvent.Size(m)
}
func (m *SyncEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SyncEvent proto.InternalMessageInfo

func (m *SyncEvent) GetFromServer() string {
	if m != nil {
		return m.FromServer
	}
	return ""
}

func (m *SyncEvent) GetToServer() string {
	if m != nil {
		return m.ToServer
	}
	return ""
}

func (m *SyncEvent) GetState() SyncEvent_SyncState {
	if m != nil {
		return m.State
	}
	return SyncEvent_UNKNOWN
}

func (m *SyncEvent) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *SyncEvent) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type AddSyncRequest struct {
	Sync                 *Sync    `protobuf:"bytes,1,opt,name=sync,proto3" json:"sync,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSyncRequest) Reset()         { *m = AddSyncRequest{} }
func (m *AddSyncRequest) String() string { return proto.CompactTextString(m) }
func (*AddSyncRequest) ProtoMessage()    {}
func (*AddSyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c01ab58cc791b3a, []int{3}
}

func (m *AddSyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSyncRequest.Unmarshal(m, b)
}
func (m *AddSyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSyncRequest.Marshal(b, m, deterministic)
}
func (m *AddSyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSyncRequest.Merge(m, src)
}
func (m *AddSyncRequest) XXX_Size() int {
	return xxx_messageInfo_AddSyncRequest.Size(m)
}
func (m *AddSyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSyncRequest proto.InternalMessageInfo

func (m *AddSyncRequest) GetSync() *Sync {
	if m != nil {
		return m.Sync
	}
	return nil
}

type AddSyncResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSyncResponse) Reset()         { *m = AddSyncResponse{} }
func (m *AddSyncResponse) String() string { return proto.CompactTextString(m) }
func (*AddSyncResponse) ProtoMessage()    {}
func (*AddSyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c01ab58cc791b3a, []int{4}
}

func (m *AddSyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSyncResponse.Unmarshal(m, b)
}
func (m *AddSyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSyncResponse.Marshal(b, m, deterministic)
}
func (m *AddSyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSyncResponse.Merge(m, src)
}
func (m *AddSyncResponse) XXX_Size() int {
	return xxx_messageInfo_AddSyncResponse.Size(m)
}
func (m *AddSyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddSyncResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("dirsync.SyncEvent_SyncState", SyncEvent_SyncState_name, SyncEvent_SyncState_value)
	proto.RegisterType((*Config)(nil), "dirsync.Config")
	proto.RegisterType((*Sync)(nil), "dirsync.Sync")
	proto.RegisterType((*SyncEvent)(nil), "dirsync.SyncEvent")
	proto.RegisterType((*AddSyncRequest)(nil), "dirsync.AddSyncRequest")
	proto.RegisterType((*AddSyncResponse)(nil), "dirsync.AddSyncResponse")
}

func init() { proto.RegisterFile("dirsync.proto", fileDescriptor_1c01ab58cc791b3a) }

var fileDescriptor_1c01ab58cc791b3a = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0xed, 0xc6, 0xc9, 0x7e, 0x4c, 0xd2, 0xb0, 0xcc, 0x01, 0x5c, 0x3e, 0xc4, 0xb2, 0x70, 0x58,
	0x71, 0xe8, 0x21, 0x3d, 0x83, 0x84, 0xd2, 0x48, 0x54, 0x94, 0x6d, 0xb5, 0x09, 0x42, 0x9c, 0x56,
	0x69, 0xd6, 0x45, 0x2b, 0x11, 0xbb, 0xd8, 0xde, 0x4a, 0xfd, 0x73, 0xfc, 0x2c, 0xce, 0x68, 0xec,
	0x6d, 0xd4, 0x2a, 0x37, 0xcf, 0x7b, 0xcf, 0xf3, 0xe6, 0x8d, 0x0d, 0x87, 0x4d, 0xab, 0xcd, 0x9d,
	0xdc, 0x1c, 0xdf, 0x68, 0x65, 0x15, 0x46, 0x7d, 0x99, 0x7f, 0x81, 0x70, 0xae, 0xe4, 0x75, 0xfb,
	0x0b, 0xdf, 0xc1, 0x88, 0x10, 0xc3, 0x83, 0x8c, 0x15, 0xe3, 0xd9, 0xe1, 0xf1, 0xfd, 0x8d, 0xe5,
	0x9d, 0xdc, 0x54, 0x9e, 0xc3, 0x23, 0x88, 0x7f, 0xaf, 0x8d, 0xad, 0x75, 0x27, 0xf9, 0x20, 0x0b,
	0x0a, 0x56, 0x45, 0x54, 0x57, 0x9d, 0xcc, 0xff, 0x06, 0x30, 0x24, 0x29, 0xa6, 0xc0, 0x9a, 0x56,
	0xf3, 0x20, 0x0b, 0x8a, 0xa4, 0xa2, 0x23, 0x3e, 0x83, 0xd0, 0x74, 0x57, 0x04, 0x0e, 0x1c, 0xd8,
	0x57, 0xc8, 0x21, 0x32, 0x42, 0xdf, 0x0a, 0x6d, 0x38, 0xcb, 0x58, 0x91, 0x54, 0xf7, 0x25, 0xbe,
	0x87, 0xa9, 0xf3, 0x21, 0xd7, 0xda, 0xb6, 0x5b, 0xc1, 0x87, 0xce, 0x6d, 0x42, 0x28, 0xb9, 0xac,
	0xda, 0xad, 0xc0, 0x0c, 0x26, 0xc4, 0xd5, 0x56, 0x39, 0x21, 0x1f, 0x65, 0xac, 0x60, 0x15, 0x10,
	0xb6, 0x52, 0x6e, 0x96, 0x0f, 0x10, 0x8a, 0x5b, 0x21, 0xad, 0xe1, 0xa1, 0x4b, 0x85, 0x8f, 0x52,
	0x2d, 0x88, 0xaa, 0x7a, 0x45, 0xfe, 0x2f, 0x80, 0x64, 0x87, 0xe2, 0x1b, 0x18, 0x5f, 0x6b, 0xb5,
	0xad, 0xfd, 0x44, 0x7d, 0x1a, 0x20, 0x68, 0xe9, 0x10, 0x7c, 0x09, 0x09, 0xf9, 0x7a, 0xda, 0xe7,
	0x8a, 0xad, 0xea, 0xc9, 0x19, 0x8c, 0x8c, 0x5d, 0x5b, 0xc1, 0x59, 0x16, 0x14, 0xd3, 0xd9, 0xab,
	0x7d, 0x5b, 0x77, 0x5a, 0x92, 0xa6, 0xf2, 0x52, 0x7c, 0x0d, 0x60, 0xec, 0x5a, 0xdb, 0x87, 0x79,
	0x13, 0x87, 0xb8, 0xb0, 0x47, 0x10, 0x0b, 0xd9, 0x78, 0x72, 0xe4, 0x57, 0x2f, 0x64, 0x43, 0x54,
	0xfe, 0xd1, 0x0f, 0xee, 0xba, 0xe1, 0x18, 0xa2, 0xef, 0xe5, 0xd7, 0xf2, 0xe2, 0x47, 0x99, 0x1e,
	0x60, 0x0c, 0xc3, 0xb3, 0xd3, 0xf3, 0x45, 0x1a, 0x10, 0x7c, 0x56, 0xd6, 0xcb, 0x9f, 0xe5, 0x3c,
	0x1d, 0xe0, 0x04, 0xe2, 0xf9, 0xc5, 0xb7, 0xcb, 0xf3, 0xc5, 0x6a, 0x91, 0xb2, 0xfc, 0x04, 0xa6,
	0x9f, 0x9b, 0xc6, 0x3d, 0xb3, 0xf8, 0xd3, 0x09, 0x63, 0xf1, 0x2d, 0x0c, 0xdd, 0x42, 0x29, 0xf5,
	0xde, 0x57, 0x70, 0x54, 0xfe, 0x14, 0x9e, 0xec, 0x2e, 0x99, 0x1b, 0x25, 0x8d, 0x98, 0x5d, 0xc2,
	0xf4, 0xd4, 0x0b, 0x69, 0x0b, 0xed, 0x46, 0xe0, 0x27, 0x88, 0x7a, 0x11, 0x3e, 0xdf, 0x35, 0x79,
	0xec, 0xf5, 0x82, 0xef, 0x13, 0xbe, 0x5f, 0x7e, 0x70, 0x15, 0xba, 0xdf, 0x7a, 0xf2, 0x3f, 0x00,
	0x00, 0xff, 0xff, 0xea, 0xe1, 0xf4, 0xeb, 0xbe, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DirsyncServiceClient is the client API for DirsyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DirsyncServiceClient interface {
	AddSync(ctx context.Context, in *AddSyncRequest, opts ...grpc.CallOption) (*AddSyncResponse, error)
}

type dirsyncServiceClient struct {
	cc *grpc.ClientConn
}

func NewDirsyncServiceClient(cc *grpc.ClientConn) DirsyncServiceClient {
	return &dirsyncServiceClient{cc}
}

func (c *dirsyncServiceClient) AddSync(ctx context.Context, in *AddSyncRequest, opts ...grpc.CallOption) (*AddSyncResponse, error) {
	out := new(AddSyncResponse)
	err := c.cc.Invoke(ctx, "/dirsync.DirsyncService/AddSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirsyncServiceServer is the server API for DirsyncService service.
type DirsyncServiceServer interface {
	AddSync(context.Context, *AddSyncRequest) (*AddSyncResponse, error)
}

func RegisterDirsyncServiceServer(s *grpc.Server, srv DirsyncServiceServer) {
	s.RegisterService(&_DirsyncService_serviceDesc, srv)
}

func _DirsyncService_AddSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirsyncServiceServer).AddSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dirsync.DirsyncService/AddSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirsyncServiceServer).AddSync(ctx, req.(*AddSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DirsyncService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dirsync.DirsyncService",
	HandlerType: (*DirsyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSync",
			Handler:    _DirsyncService_AddSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dirsync.proto",
}
