// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dirsync.proto

package dirsync

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	Syncs                []*Sync  `protobuf:"bytes,1,rep,name=syncs,proto3" json:"syncs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c01ab58cc791b3a, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetSyncs() []*Sync {
	if m != nil {
		return m.Syncs
	}
	return nil
}

type Sync struct {
	Dir                  string   `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Subdir               string   `protobuf:"bytes,2,opt,name=subdir,proto3" json:"subdir,omitempty"`
	Servers              []string `protobuf:"bytes,3,rep,name=servers,proto3" json:"servers,omitempty"`
	LastSyncTime         int64    `protobuf:"varint,4,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	TimeToSync           []int64  `protobuf:"varint,5,rep,packed,name=time_to_sync,json=timeToSync,proto3" json:"time_to_sync,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sync) Reset()         { *m = Sync{} }
func (m *Sync) String() string { return proto.CompactTextString(m) }
func (*Sync) ProtoMessage()    {}
func (*Sync) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c01ab58cc791b3a, []int{1}
}

func (m *Sync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sync.Unmarshal(m, b)
}
func (m *Sync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sync.Marshal(b, m, deterministic)
}
func (m *Sync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sync.Merge(m, src)
}
func (m *Sync) XXX_Size() int {
	return xxx_messageInfo_Sync.Size(m)
}
func (m *Sync) XXX_DiscardUnknown() {
	xxx_messageInfo_Sync.DiscardUnknown(m)
}

var xxx_messageInfo_Sync proto.InternalMessageInfo

func (m *Sync) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *Sync) GetSubdir() string {
	if m != nil {
		return m.Subdir
	}
	return ""
}

func (m *Sync) GetServers() []string {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *Sync) GetLastSyncTime() int64 {
	if m != nil {
		return m.LastSyncTime
	}
	return 0
}

func (m *Sync) GetTimeToSync() []int64 {
	if m != nil {
		return m.TimeToSync
	}
	return nil
}

type AddSyncRequest struct {
	Sync                 *Sync    `protobuf:"bytes,1,opt,name=sync,proto3" json:"sync,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSyncRequest) Reset()         { *m = AddSyncRequest{} }
func (m *AddSyncRequest) String() string { return proto.CompactTextString(m) }
func (*AddSyncRequest) ProtoMessage()    {}
func (*AddSyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c01ab58cc791b3a, []int{2}
}

func (m *AddSyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSyncRequest.Unmarshal(m, b)
}
func (m *AddSyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSyncRequest.Marshal(b, m, deterministic)
}
func (m *AddSyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSyncRequest.Merge(m, src)
}
func (m *AddSyncRequest) XXX_Size() int {
	return xxx_messageInfo_AddSyncRequest.Size(m)
}
func (m *AddSyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSyncRequest proto.InternalMessageInfo

func (m *AddSyncRequest) GetSync() *Sync {
	if m != nil {
		return m.Sync
	}
	return nil
}

type AddSyncResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSyncResponse) Reset()         { *m = AddSyncResponse{} }
func (m *AddSyncResponse) String() string { return proto.CompactTextString(m) }
func (*AddSyncResponse) ProtoMessage()    {}
func (*AddSyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c01ab58cc791b3a, []int{3}
}

func (m *AddSyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSyncResponse.Unmarshal(m, b)
}
func (m *AddSyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSyncResponse.Marshal(b, m, deterministic)
}
func (m *AddSyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSyncResponse.Merge(m, src)
}
func (m *AddSyncResponse) XXX_Size() int {
	return xxx_messageInfo_AddSyncResponse.Size(m)
}
func (m *AddSyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddSyncResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Config)(nil), "dirsync.Config")
	proto.RegisterType((*Sync)(nil), "dirsync.Sync")
	proto.RegisterType((*AddSyncRequest)(nil), "dirsync.AddSyncRequest")
	proto.RegisterType((*AddSyncResponse)(nil), "dirsync.AddSyncResponse")
}

func init() { proto.RegisterFile("dirsync.proto", fileDescriptor_1c01ab58cc791b3a) }

var fileDescriptor_1c01ab58cc791b3a = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x09, 0x6e, 0x13, 0xf5, 0x68, 0x03, 0xdc, 0x00, 0x16, 0x93, 0x31, 0x0c, 0x5e, 0xe8,
	0xd0, 0xee, 0x48, 0x08, 0x7e, 0x00, 0x72, 0xbb, 0x47, 0x34, 0x31, 0xc8, 0x12, 0x8d, 0x8b, 0xed,
	0x56, 0xea, 0xdf, 0xe0, 0x17, 0xa3, 0x73, 0xd2, 0x4a, 0xa8, 0x5b, 0xde, 0x7b, 0xdf, 0xbd, 0xbb,
	0x18, 0x26, 0x8d, 0xf5, 0x61, 0xdf, 0xd6, 0xd3, 0x8d, 0x77, 0xd1, 0x61, 0xd1, 0x4b, 0xf9, 0x04,
	0xf9, 0xab, 0x6b, 0x3f, 0xed, 0x17, 0x3e, 0xc0, 0x90, 0x9c, 0xc0, 0x33, 0xc1, 0xd4, 0xc5, 0x6c,
	0x32, 0x3d, 0x4c, 0x2c, 0xf6, 0x6d, 0xad, 0xbb, 0x4c, 0xfe, 0x66, 0x30, 0x20, 0x8d, 0x57, 0xc0,
	0x1a, 0xeb, 0x79, 0x26, 0x32, 0x35, 0xd2, 0xf4, 0x89, 0x37, 0x90, 0x87, 0xed, 0x8a, 0xcc, 0xf3,
	0x64, 0xf6, 0x0a, 0x39, 0x14, 0xc1, 0xf8, 0x9d, 0xf1, 0x81, 0x33, 0xc1, 0xd4, 0x48, 0x1f, 0x24,
	0x3e, 0x42, 0xf9, 0xfd, 0x11, 0x62, 0x45, 0xd5, 0x55, 0xb4, 0x6b, 0xc3, 0x07, 0x22, 0x53, 0x4c,
	0x8f, 0xc9, 0xa5, 0x2d, 0x4b, 0xbb, 0x36, 0x28, 0x60, 0x4c, 0x59, 0x15, 0x5d, 0x02, 0xf9, 0x50,
	0x30, 0xc5, 0x34, 0x90, 0xb7, 0x74, 0x44, 0xc9, 0x39, 0x94, 0x2f, 0x4d, 0x93, 0xce, 0x34, 0x3f,
	0x5b, 0x13, 0x22, 0xde, 0xc3, 0x20, 0xb1, 0x74, 0xde, 0xc9, 0xaf, 0xa4, 0x48, 0x5e, 0xc3, 0xe5,
	0x71, 0x28, 0x6c, 0x5c, 0x1b, 0xcc, 0xec, 0x1d, 0xca, 0xb7, 0x0e, 0x5c, 0x18, 0xbf, 0xb3, 0xb5,
	0xc1, 0x67, 0x28, 0x7a, 0x08, 0x6f, 0x8f, 0x25, 0xff, 0x77, 0xdd, 0xf1, 0xd3, 0xa0, 0xeb, 0x93,
	0x67, 0xab, 0x3c, 0xbd, 0xf6, 0xfc, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x89, 0xd2, 0x91, 0x5f, 0x7e,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DirsyncServiceClient is the client API for DirsyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DirsyncServiceClient interface {
	AddSync(ctx context.Context, in *AddSyncRequest, opts ...grpc.CallOption) (*AddSyncResponse, error)
}

type dirsyncServiceClient struct {
	cc *grpc.ClientConn
}

func NewDirsyncServiceClient(cc *grpc.ClientConn) DirsyncServiceClient {
	return &dirsyncServiceClient{cc}
}

func (c *dirsyncServiceClient) AddSync(ctx context.Context, in *AddSyncRequest, opts ...grpc.CallOption) (*AddSyncResponse, error) {
	out := new(AddSyncResponse)
	err := c.cc.Invoke(ctx, "/dirsync.DirsyncService/AddSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirsyncServiceServer is the server API for DirsyncService service.
type DirsyncServiceServer interface {
	AddSync(context.Context, *AddSyncRequest) (*AddSyncResponse, error)
}

func RegisterDirsyncServiceServer(s *grpc.Server, srv DirsyncServiceServer) {
	s.RegisterService(&_DirsyncService_serviceDesc, srv)
}

func _DirsyncService_AddSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirsyncServiceServer).AddSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dirsync.DirsyncService/AddSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirsyncServiceServer).AddSync(ctx, req.(*AddSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DirsyncService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dirsync.DirsyncService",
	HandlerType: (*DirsyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSync",
			Handler:    _DirsyncService_AddSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dirsync.proto",
}
